config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/devise/registrations'
  }

  devise_for :admins, skip: [:registrations]

  # needs to be AFTER "devise_for :admins" otherwise the admin routes will be messed up
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticate :user do
    resources :campaigns, only: [:index, :show] do
      member do
        get '/performance' => 'campaigns#performance', as: 'performance'
      end
      resources :proposed_solutions, only: [:new, :create]
      collection do
        get '/search' => 'search#find_campaigns', as: 'search'
      end
    end
    resources :favorites, only: [:index]
    scope '/favorites' do
      post '/add-to-favorites' => 'favorites#add_to_favorites'
      delete '/remove-from-favorites' => 'favorites#remove_from_favorites'
    end
  end

  authenticated :user do
    root to: 'campaigns#index', as: :authenticated_root
  end

  root 'home#index'
end

app/models/proposed_solution.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: proposed_solutions
#
#  id                        :integer          not null, primary key
#  user_id                   :integer
#  campaign_id               :integer
#  link                      :string(255)
#  technology_description    :text(65535)
#  technology_application    :text(65535)
#  patents                   :text(65535)
#  trl                       :string(255)
#  licence_available         :string(255)
#  institution               :string(255)
#  expectations              :text(65535)
#  percent_match             :integer
#  reviewed                  :boolean
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  attachment_1_file_name    :string(255)
#  attachment_1_content_type :string(255)
#  attachment_1_file_size    :integer
#  attachment_1_updated_at   :datetime
#  attachment_2_file_name    :string(255)
#  attachment_2_content_type :string(255)
#  attachment_2_file_size    :integer
#  attachment_2_updated_at   :datetime
#  attachment_3_file_name    :string(255)
#  attachment_3_content_type :string(255)
#  attachment_3_file_size    :integer
#  attachment_3_updated_at   :datetime
#
# Indexes
#
#  index_proposed_solutions_on_campaign_id  (campaign_id)
#  index_proposed_solutions_on_user_id      (user_id)
#

class ProposedSolution < ActiveRecord::Base
  delegate :url_helpers, to: 'Rails.application.routes'

  #------------------------------------------------------------------------------
  # Associations
  belongs_to :user
  belongs_to :campaign
  has_attached_file :attachment_1
  has_attached_file :attachment_2
  has_attached_file :attachment_3

  #------------------------------------------------------------------------------
  # Scopes
  scope :reviewed, -> { where(reviewed: true) }

  #------------------------------------------------------------------------------
  # Validations
  validates_attachment :attachment_1, content_type: { content_type: %w(image/jpeg image/png application/pdf application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet application/vnd.ms-powerpoint application/vnd.openxmlformats-officedocument.presentationml.presentation application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) },
                                      message: 'File must be .pdf, .doc, .docx, .ppt, .pptx, .jpg, .png, .xls, .xlsx'
  validates_attachment :attachment_2, content_type: { content_type: %w(image/jpeg image/png application/pdf application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet application/vnd.ms-powerpoint application/vnd.openxmlformats-officedocument.presentationml.presentation application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) },
                                      message: 'File must be .pdf, .doc, .docx, .ppt, .pptx, .jpg, .png, .xls, .xlsx'
  validates_attachment :attachment_3, content_type: { content_type: %w(image/jpeg image/png application/pdf application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet application/vnd.ms-powerpoint application/vnd.openxmlformats-officedocument.presentationml.presentation application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) },
                                      message: 'File must be .pdf, .doc, .docx, .ppt, .pptx, .jpg, .png, .xls, .xlsx'

  validates :user_id, :campaign_id, :technology_description, :technology_application, :trl, presence: true

  #------------------------------------------------------------------------------
  # Callbacks
  after_create :send_email_to_admin

  #------------------------------------------------------------------------------
  # Enumerations

  #------------------------------------------------------------------------------
  # AASM definitions

  #------------------------------------------------------------------------------
  # Class methods
  def self.trl_options
    ['TRL 0: Idea',
     'TRL 1: Basic research',
     'TRL 2: Technology formulation',
     'TRL 3: Applied research',
     'TRL 4: Small scale prototype',
     'TRL 5: Large scale prototype',
     'TRL 6: Prototype system',
     'TRL 7: Demonstration system',
     'TRL 8: First of a kind commercial system',
     'TRL 9: Full commercial application']
  end

  #------------------------------------------------------------------------------
  # Instance methods

  #------------------------------------------------------------------------------
  # Rails Admin Config
  rails_admin do
    list do
      field :id
      field :reviewed
      field :user do
        label 'Name'
      end
      field :campaign do
        label 'Title'
      end
      field :link
      field :attachment_1
      field :attachment_2
      field :attachment_3
      field :technology_description
      field :technology_application
      field :patents
      field :trl, :enum do
        enum do
          ProposedSolution.trl_options
        end
      end
      field :licence_available
      field :institution
      field :expectations
      field :percent_match
      field :created_at
    end

    show do
      field :id
      field :reviewed
      field :user do
        label 'Name'
      end
      field :campaign do
        label 'Title'
      end
      field :link
      field :attachment_1
      field :attachment_2
      field :attachment_3
      field :technology_description
      field :technology_application
      field :patents
      field :trl, :enum do
        enum do
          ProposedSolution.trl_options
        end
      end
      field :licence_available
      field :institution
      field :expectations
      field :percent_match
      field :created_at
    end

    edit do
      field :reviewed
      field :user do
        label 'Name'
      end
      field :campaign do
        label 'Title'
      end
      field :link
      field :attachment_1
      field :attachment_2
      field :attachment_3
      field :technology_description
      field :technology_application
      field :patents
      field :trl, :enum do
        enum do
          ProposedSolution.trl_options
        end
      end
      field :licence_available
      field :institution
      field :expectations
      field :percent_match
    end

    export do
      field :id
      field :reviewed
      field :user do
        label 'Name'
      end
      field :campaign do
        label 'Title'
      end
      field :link
      field :attachment_1
      field :attachment_2
      field :attachment_3
      field :technology_description
      field :technology_application
      field :patents
      field :trl, :enum do
        enum do
          ProposedSolution.trl_options
        end
      end
      field :licence_available
      field :institution
      field :expectations
      field :percent_match
      field :created_at
    end
  end

  #------------------------------------------------------------------------------
  private

  def send_email_to_admin
    ApplicationMailer.sendgrid_send(
      to: 'chantal@baehl-innovation.com',
      template_id: '850a599b-da08-4c68-82c3-60b1d2ed2ed0',
      substitutions: {
        '-firstName-': user.first_name,
        '-lastName-': user.last_name,
        '-link-': link.present? ? "Here is the link associated with the proposed solution: #{link}" : ' ',
        '-attachment1-': attachment_1.present? ? "Here is an attachment associated with the proposed solution: #{attachment_1}" : ' ',
        '-attachment2-': attachment_2.present? ? "Here is an attachment associated with the proposed solution: #{attachment_2}" : ' ',
        '-attachment3-': attachment_3.present? ? "Here is an attachment associated with the proposed solution: #{attachment_3}" : ' ',
        '-url-': url_helpers.new_admin_session_url
      }
    ).deliver_now
  end
end

app/controllers/proposed_solutions_controller.rb
# frozen_string_literal: true
class ProposedSolutionsController < ApplicationController
  # rubocop:disable Metrics/AbcSize
  # GET /proposed_solutions/new
  def new
    if current_user.role == :tech_provider
      number_of_proposed_solutions = params[:number_of_proposed_solutions].present? ? params[:number_of_proposed_solutions].to_i : 1
      @campaign = Campaign.active.find_by(id: params[:campaign_id])
      @proposed_solutions = []
      number_of_proposed_solutions.times do
        @proposed_solutions << current_user.proposed_solutions.new(campaign_id: @campaign.id)
      end
    elsif current_user.role == :tech_seeker
      flash[:error] = 'Something went wrong. Please try again.'
      redirect_to campaigns_path
    end
  end
  # rubocop:enable Metrics/AbcSize

  # rubocop:disable Metrics/AbcSize
  # POST /proposed_solutions
  def create
    if current_user.role == :tech_provider
      @campaign = Campaign.active.find_by(id: params[:campaign_id])

      begin
        ActiveRecord::Base.transaction do
          params[:proposed_solutions].each do |proposed_solution|
            current_user.proposed_solutions.create!(proposed_solution_params(proposed_solution))
          end
        end
        respond_to do |format|
          format.html { redirect_to campaigns_path, notice: 'Proposed solution was successfully created.' }
        end
      rescue ActiveRecord::RecordInvalid => e
        flash[:error] = "Something went wrong. Please try again and fill in required fields. #{e.message}"
        redirect_to new_campaign_proposed_solution_path(@campaign)
      end

    elsif current_user.role == :tech_seeker
      flash[:error] = 'Something went wrong. Please try again.'
      redirect_to campaigns_path
    end
  end
  # rubocop:enable Metrics/AbcSize

  private

  def proposed_solution_params(params)
    params.permit(:campaign_id, :link, :attachment_1, :attachment_2, :attachment_3, :technology_description, :technology_application, :patents, :trl, :licence_available, :institution, :expectations)
  end
end

app/views/proposed_solutions/new.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading.text-center
        %h2 Interested? Apply Now
      .panel-body
        .row
          .col-md-12.text-center
            %p.number-of You have
            = select_tag :number, options_for_select(1..10, params[:number_of_proposed_solutions]), class: 'select2-ps number-of-proposed-solutions', data: { url: new_campaign_proposed_solution_path(@campaign) }
            %p.number-of potential technologies/solutions available
            %p Please provide links to the technologies or proposed solutions, if you already have info about them available online, or, please attach document(s) with the detailed information.
        = simple_form_for(@proposed_solutions, url: campaign_proposed_solutions_path, method: :post, html: { multipart: true }) do |f|
          - @proposed_solutions.each do |proposed_solution|
            = simple_fields_for 'proposed_solutions[]', proposed_solution do |p|
              = p.error_notification
              = p.input :campaign_id, as: :hidden, input_html: { value: proposed_solution.campaign.id }
              .row.proposed-solution-form-title
                .col-xs-offset-4.col-xs-4.text-center
                  %h2 Proposed Solution
              .row.proposed-solution-form
                .col-xs-offset-2.col-xs-4
                  %p Link (optional):
                .col-xs-4
                  = p.input :link, required: true, label: false
              .row
                .col-xs-offset-2.col-xs-4
                  %p Attachment #1 (optional):
                .col-xs-4
                  = p.input :attachment_1, label: false, input_html: { accept: '.png, .pdf, .doc, .docx, .ppt, .pptx, .jpg, .xls, .xlsx' }
                  %p.info-label
                    %em Eg. Invention background, preliminary results, non-confidential info sheet, press release, or other relevant documents.
              .row
                .col-xs-offset-2.col-xs-4
                  %p Attachment #2 (optional):
                .col-xs-4
                  = p.input :attachment_2, label: false, input_html: { accept: '.png, .pdf, .doc, .docx, .ppt, .pptx, .jpg, .xls, .xlsx' }
                  %p.info-label
                    %em Eg. Invention background, preliminary results, non-confidential info sheet, press release, or other relevant documents.
              .row
                .col-xs-offset-2.col-xs-4
                  %p Attachment #3 (optional):
                .col-xs-4
                  = p.input :attachment_3, label: false, input_html: { accept: '.png, .pdf, .doc, .docx, .ppt, .pptx, .jpg, .xls, .xlsx' }
                  %p.info-label
                    %em Eg. Invention background, preliminary results, non-confidential info sheet, press release, or other relevant documents.
              .row
                .col-xs-offset-2.col-xs-4
                  %p What is your technology? (required)
                  %p.info-label
                    %em Include information on whether your technology is disruptive or incremental.
                .col-xs-4
                  = p.input :technology_description, required: true, label: false, input_html: { rows: 5 }
              .row
                .col-xs-offset-2.col-xs-4
                  %p What is it's main application (required)
                .col-xs-4
                  = p.input :technology_application, required: true, label: false
              .row
                .col-xs-offset-2.col-xs-4
                  %p Patents (optional):
                .col-xs-4
                  = p.input :patents, label: false
              .row
                .col-xs-offset-2.col-xs-4
                  %p{ style: 'display: inline-block' } TRL: (required)
                  = link_to '#', style: 'display: inline-block' do
                    %sup= fa_icon 'info-circle', class: 'fa-2x trl-modal'
                .col-xs-4
                  = p.input :trl, required: true, label: false, include_blank: 'Select one', collection: ProposedSolution.trl_options, input_html: { class: 'select2' }
              .row
                .col-xs-offset-2.col-xs-4
                  %p Licence available (optional):
                .col-xs-4
                  = p.input :licence_available, label: false, include_blank: 'Select one', collection: ['Yes', 'No'], input_html: { class: 'select2' }
              .row
                .col-xs-offset-2.col-xs-4
                  %p What institution/start-up is developing the technology? (optional)
                .col-xs-4
                  = p.input :institution, label: false
              .row
                .col-xs-offset-2.col-xs-4
                  %p Your Expectations (optional)
                .col-xs-4
                  = p.input :expectations, label: false, input_html: { rows: 10 }
          .row
            .col-md-12.text-center
              = f.button :submit, 'Apply Now', class: 'btn btn-primary proposed-solution-button'