config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/devise/registrations'
  }

  devise_for :admins, skip: [:registrations]

  # needs to be AFTER "devise_for :admins" otherwise the admin routes will be messed up
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticate :user do
    resources :campaigns, only: [:index, :show] do
      member do
        get '/performance' => 'campaigns#performance', as: 'performance'
      end
      resources :proposed_solutions, only: [:new, :create]
      collection do
        get '/search' => 'search#find_campaigns', as: 'search'
      end
    end
    resources :favorites, only: [:index]
    scope '/favorites' do
      post '/add-to-favorites' => 'favorites#add_to_favorites'
      delete '/remove-from-favorites' => 'favorites#remove_from_favorites'
    end
  end

  authenticated :user do
    root to: 'campaigns#index', as: :authenticated_root
  end

  root 'home#index'
end

app/models/campaign.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: campaigns
#
#  id                          :integer          not null, primary key
#  user_id                     :integer
#  title                       :string(255)
#  featured_image_updated_at   :datetime
#  featured_image_file_size    :integer
#  featured_image_content_type :string(255)
#  featured_image_file_name    :string(255)
#  company_description         :text(65535)
#  company_needs               :text(65535)
#  company_challenges          :text(65535)
#  sector                      :string(255)
#  country                     :string(255)
#  targeted_time_to_market     :string(255)
#  expected_trl                :string(255)
#  state                       :string(255)
#  cost                        :string(255)
#  meeting_requests            :integer
#  next_meeting                :datetime
#  expires_at                  :datetime
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#
# Indexes
#
#  index_campaigns_on_user_id  (user_id)
#

class Campaign < ActiveRecord::Base
  include ClassyEnum::ActiveRecord
  extend Enumerize
  delegate :url_helpers, to: 'Rails.application.routes'
  serialize :sector, Array

  #------------------------------------------------------------------------------
  # Associations
  belongs_to :user
  has_many :proposed_solutions
  has_many :likes
  has_attached_file :featured_image, styles: { medium: '600x350!' }

  #------------------------------------------------------------------------------
  # Enumerations
  classy_enum_attr :state, allow_blank: false, allow_nil: false, default: :pending
  enumerize :sector, in: [:devices, :cosmetic, :ehealth, :pharmaceuticals, :biopharmaceuticals, :agrifood, :aerospace, :automotive, :bioproducts, :chemicals, :digital_tech, :machinery_equipment, :energy, :telecom, :nutraceuticals, :other], multiple: true, i18n_scope: 'sector'

  #------------------------------------------------------------------------------
  # Scopes
  scope :active, -> { where(state: 'active') }
  scope :not_deleted, -> { where(state: %w(active expired pending)) }

  #------------------------------------------------------------------------------
  # Validations
  validates :user_id, :expires_at, :title, :company_description, :company_needs, :sector, :targeted_time_to_market, :expected_trl, presence: true
  validates_attachment_content_type :featured_image, content_type: /^image\/(jpg|jpeg|png)$/
  validates :featured_image, attachment_presence: true

  #------------------------------------------------------------------------------
  # Callbacks
  after_create :send_email_to_user_on_active, :send_email_to_user_with_interests
  after_update :send_email_to_user_on_active, :send_email_to_user_with_interests

  #------------------------------------------------------------------------------
  # Enumerations

  #------------------------------------------------------------------------------
  # AASM definitions

  #------------------------------------------------------------------------------
  # Class methods
  # rubocop:disable MethodLength
  def self.country_options
    [
      { id: 'Europe', text: 'Europe' },
      { id: 'Afghanistan', text: 'Afghanistan' },
      { id: 'Aland Islands', text: 'Aland Islands' },
      { id: 'Albania', text: 'Albania' },
      { id: 'Algeria', text: 'Algeria' },
      { id: 'American Samoa', text: 'American Samoa' },
      { id: 'Andorra', text: 'Andorra' },
      { id: 'Angola', text: 'Angola' },
      { id: 'Anguilla', text: 'Anguilla' },
      { id: 'Antarctica', text: 'Antarctica' },
      { id: 'Antigua And Barbuda', text: 'Antigua And Barbuda' },
      { id: 'Argentina', text: 'Argentina' },
      { id: 'Armenia', text: 'Armenia' },
      { id: 'Aruba', text: 'Aruba' },
      { id: 'Australia', text: 'Australia' },
      { id: 'Austria', text: 'Austria' },
      { id: 'Azerbaijan', text: 'Azerbaijan' },
      { id: 'Bahamas', text: 'Bahamas' },
      { id: 'Bahrain', text: 'Bahrain' },
      { id: 'Bangladesh', text: 'Bangladesh' },
      { id: 'Barbados', text: 'Barbados' },
      { id: 'Belarus', text: 'Belarus' },
      { id: 'Belgium', text: 'Belgium' },
      { id: 'Belize', text: 'Belize' },
      { id: 'Benin', text: 'Benin' },
      { id: 'Bermuda', text: 'Bermuda' },
      { id: 'Bhutan', text: 'Bhutan' },
      { id: 'Bolivia', text: 'Bolivia' },
      { id: 'Bosnia And Herzegovina', text: 'Bosnia And Herzegovina' },
      { id: 'Botswana', text: 'Botswana' },
      { id: 'Bouvet Island', text: 'Bouvet Island' },
      { id: 'Brazil', text: 'Brazil' },
      { id: 'British Indian Ocean Territory', text: 'British Indian Ocean Territory' },
      { id: 'Brunei Darussalam', text: 'Brunei Darussalam' },
      { id: 'Bulgaria', text: 'Bulgaria' },
      { id: 'Burkina Faso', text: 'Burkina Faso' },
      { id: 'Burundi', text: 'Burundi' },
      { id: 'Cambodia', text: 'Cambodia' },
      { id: 'Cameroon', text: 'Cameroon' },
      { id: 'Canada', text: 'Canada' },
      { id: 'Cape Verde', text: 'Cape Verde' },
      { id: 'Cayman Islands', text: 'Cayman Islands' },
      { id: 'Central African Republic', text: 'Central African Republic' },
      { id: 'Chad', text: 'Chad' },
      { id: 'Chile', text: 'Chile' },
      { id: 'China', text: 'China' },
      { id: 'Christmas Island', text: 'Christmas Island' },
      { id: 'Cocos (Keeling) Islands', text: 'Cocos (Keeling) Islands' },
      { id: 'Colombia', text: 'Colombia' },
      { id: 'Comoros', text: 'Comoros' },
      { id: 'Congo', text: 'Congo' },
      { id: 'Congo}, Democratic Republic', text: 'Congo}, Democratic Republic' },
      { id: 'Cook Islands', text: 'Cook Islands' },
      { id: 'Costa Rica', text: 'Costa Rica' },
      { id: 'Cote D\'Ivoire', text: 'Cote D\'Ivoire' },
      { id: 'Croatia', text: 'Croatia' },
      { id: 'Cuba', text: 'Cuba' },
      { id: 'Cyprus', text: 'Cyprus' },
      { id: 'Czech Republic', text: 'Czech Republic' },
      { id: 'Denmark', text: 'Denmark' },
      { id: 'Djibouti', text: 'Djibouti' },
      { id: 'Dominica', text: 'Dominica' },
      { id: 'Dominican Republic', text: 'Dominican Republic' },
      { id: 'Ecuador', text: 'Ecuador' },
      { id: 'Egypt', text: 'Egypt' },
      { id: 'El Salvador', text: 'El Salvador' },
      { id: 'Equatorial Guinea', text: 'Equatorial Guinea' },
      { id: 'Eritrea', text: 'Eritrea' },
      { id: 'Estonia', text: 'Estonia' },
      { id: 'Ethiopia', text: 'Ethiopia' },
      { id: 'Falkland Islands (Malvinas)', text: 'Falkland Islands (Malvinas)' },
      { id: 'Faroe Islands', text: 'Faroe Islands' },
      { id: 'Fiji', text: 'Fiji' },
      { id: 'Finland', text: 'Finland' },
      { id: 'France', text: 'France' },
      { id: 'French Guiana', text: 'French Guiana' },
      { id: 'French Polynesia', text: 'French Polynesia' },
      { id: 'French Southern Territories', text: 'French Southern Territories' },
      { id: 'Gabon', text: 'Gabon' },
      { id: 'Gambia', text: 'Gambia' },
      { id: 'Georgia', text: 'Georgia' },
      { id: 'Germany', text: 'Germany' },
      { id: 'Ghana', text: 'Ghana' },
      { id: 'Gibraltar', text: 'Gibraltar' },
      { id: 'Greece', text: 'Greece' },
      { id: 'Greenland', text: 'Greenland' },
      { id: 'Grenada', text: 'Grenada' },
      { id: 'Guadeloupe', text: 'Guadeloupe' },
      { id: 'Guam', text: 'Guam' },
      { id: 'Guatemala', text: 'Guatemala' },
      { id: 'Guernsey', text: 'Guernsey' },
      { id: 'Guinea', text: 'Guinea' },
      { id: 'Guinea-Bissau', text: 'Guinea-Bissau' },
      { id: 'Guyana', text: 'Guyana' },
      { id: 'Haiti', text: 'Haiti' },
      { id: 'Heard Island & Mcdonald Islands', text: 'Heard Island & Mcdonald Islands' },
      { id: 'Holy See (Vatican City State)', text: 'Holy See (Vatican City State)' },
      { id: 'Honduras', text: 'Honduras' },
      { id: 'Hong Kong', text: 'Hong Kong' },
      { id: 'Hungary', text: 'Hungary' },
      { id: 'Iceland', text: 'Iceland' },
      { id: 'India', text: 'India' },
      { id: 'Indonesia', text: 'Indonesia' },
      { id: 'Iran, Islamic Republic Of', text: 'Iran, Islamic Republic Of' },
      { id: 'Iraq', text: 'Iraq' },
      { id: 'Ireland', text: 'Ireland' },
      { id: 'Isle Of Man', text: 'Isle Of Man' },
      { id: 'Israel', text: 'Israel' },
      { id: 'Italy', text: 'Italy' },
      { id: 'Jamaica', text: 'Jamaica' },
      { id: 'Japan', text: 'Japan' },
      { id: 'Jersey', text: 'Jersey' },
      { id: 'Jordan', text: 'Jordan' },
      { id: 'Kazakhstan', text: 'Kazakhstan' },
      { id: 'Kenya', text: 'Kenya' },
      { id: 'Kiribati', text: 'Kiribati' },
      { id: 'Korea', text: 'Korea' },
      { id: 'Kuwait', text: 'Kuwait' },
      { id: 'Kyrgyzstan', text: 'Kyrgyzstan' },
      { id: 'Lao People\'s Democratic Republic', text: 'Lao People\'s Democratic Republic' },
      { id: 'Latvia', text: 'Latvia' },
      { id: 'Lebanon', text: 'Lebanon' },
      { id: 'Lesotho', text: 'Lesotho' },
      { id: 'Liberia', text: 'Liberia' },
      { id: 'Libyan Arab Jamahiriya', text: 'Libyan Arab Jamahiriya' },
      { id: 'Liechtenstein', text: 'Liechtenstein' },
      { id: 'Lithuania', text: 'Lithuania' },
      { id: 'Luxembourg', text: 'Luxembourg' },
      { id: 'Macao', text: 'Macao' },
      { id: 'Macedonia', text: 'Macedonia' },
      { id: 'Madagascar', text: 'Madagascar' },
      { id: 'Malawi', text: 'Malawi' },
      { id: 'Malaysia', text: 'Malaysia' },
      { id: 'Maldives', text: 'Maldives' },
      { id: 'Mali', text: 'Mali' },
      { id: 'Malta', text: 'Malta' },
      { id: 'Marshall Islands', text: 'Marshall Islands' },
      { id: 'Martinique', text: 'Martinique' },
      { id: 'Mauritania', text: 'Mauritania' },
      { id: 'Mauritius', text: 'Mauritius' },
      { id: 'Mayotte', text: 'Mayotte' },
      { id: 'Mexico', text: 'Mexico' },

app/controllers/campaigns_controller.rb
# frozen_string_literal: true
class CampaignsController < ApplicationController
  after_action :track_action, only: [:show]

  # GET /campaigns
  def index
    @slider_items = SliderItem.active
    if current_user.role == :tech_provider
      @campaigns = Campaign.active.order(expires_at: :desc)
    elsif current_user.role == :tech_seeker
      @campaigns = current_user.campaigns.not_deleted
    end
  end

  # GET /campaigns/1
  # rubocop:disable Metrics/AbcSize
  def show
    if current_user.role == :tech_provider
      @campaign = Campaign.not_deleted.find(params[:id])
      @proposed_solutions = current_user.proposed_solutions.where(campaign_id: @campaign.id)
    elsif current_user.role == :tech_seeker
      @campaign = current_user.campaigns.not_deleted.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Something went wrong. This campaign might have been deleted by the administrator.'
    redirect_to campaigns_path
  end

  def performance
    @campaign = current_user.campaigns.not_deleted.find(params[:id])
    if current_user.role == :tech_seeker
      @favorites_count = @campaign.likes.count
      @proposed_solutions = @campaign.proposed_solutions
      @reviewed_proposed_solutions = @proposed_solutions.reviewed.count
      @campaign_views_count = Ahoy::Event.all.map { |event| event.properties['id'] }.count(@campaign.id.to_s)
    else
      redirect_to campaigns_path && return
    end
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Something went wrong. Please try another url'
    redirect_to campaigns_path
  end
  # rubocop:enable Metrics/AbcSize

  protected

  def track_action
    ahoy.track "Processed #{controller_name}##{action_name}", request.filtered_parameters
  end
end

app/views/campaigns/_info_box.html.haml
.info-box
  %span.info-box-icon
    = fa_icon icon.to_s
  .info-box-content
    %span.info-box-text= info_title
    %span.info-box-number= info_number

app/views/campaigns/index.html.haml
.swiper-container
  .swiper-wrapper
    - @slider_items.each do |slider_item|
      .swiper-slide
        = link_to slider_item.link do
          %h2.slider-title= slider_item.title
          = image_tag(slider_item.slide_image.url(:medium), class: 'img-responsive')

  .swiper-pagination
  .swiper-button-next
  .swiper-button-prev

- if @campaigns.present?
  = render 'shared/campaigns_grid_list', collection: @campaigns
- else
  - if current_user.role == :tech_seeker
    .container.text-center
      %h2 You have no current campaigns.
      %p.no-campaigns-message Are you interested in launching a campaign towards our community of Tech Providers? One of our consultants will be contacting you shortly to see how we can help.
      %p.no-campaigns-message Alternatively, you can contact us at: <strong>info@baehl-innovation.com</strong> or <strong>+33 1 44 10 41 43</strong>
      %p.no-campaigns-message We look forward to speaking with you soon.

app/views/campaigns/performance.html.haml
.container
  .row
    .col-md-12.text-center
      %h1 Campaign Performance
      %h2= @campaign.title
  .row
    .col-md-4.col-sm-6.col-xs-12
      = render 'info_box', info_title: 'Total Views', info_number: @campaign_views_count, icon: 'envelope-o'
    .col-md-4.col-sm-6.col-xs-12
      = render 'info_box', info_title: 'Meeting Requests', info_number: @campaign.meeting_requests.present? ? @campaign.meeting_requests : 0, icon: 'users'
    .col-md-4.col-sm-6.col-xs-12
      = render 'info_box', info_title: 'Favorites', info_number: @favorites_count, icon: 'heart'
    .col-md-4.col-sm-6.col-xs-12
      = render 'info_box', info_title: 'Campaign End Date', info_number: @campaign&.expires_at&.strftime('%b %e %Y, %l:%M %p'), icon: 'calendar'
    .col-md-4.col-sm-6.col-xs-12
      = render 'info_box', info_title: 'Next Meeting', info_number: @campaign&.next_meeting&.strftime('%b %e %Y, %l:%M %p'), icon: 'calendar-check-o'
    .col-md-4.col-sm-6.col-xs-12
      = render 'info_box', info_title: 'Cost of Campaign', info_number: @campaign.cost, icon: 'usd'

  .row
    .col-md-12.text-center
      %h1.box-title Applications to the Campaign
      .row
        .col-md-offset-2.col-md-4.col-sm-6.col-xs-12
          = render 'info_box', info_title: 'Applications Submitted', info_number: @proposed_solutions.count, icon: 'files-o'
        .col-md-4.col-sm-6.col-xs-12
          = render 'info_box', info_title: 'Applications Reviewed', info_number: @reviewed_proposed_solutions.present? ? @reviewed_proposed_solutions : 0, icon: 'refresh'
      - if @proposed_solutions.present?
        .row
          .col-md-offset-2.col-md-8.col-sm-12
            %table.table.table-bordered
              %tbody.ps-table-body
                %tr.ps-table-headings
                  %th{ style: 'width: 10px' } #
                  %th Solution Provider
                  %th Application Percent Match

                - @proposed_solutions.each_with_index do |proposed_solution, index|
                  %tr
                    %td= index + 1
                    %td= proposed_solution.user.company
                    %td
                      - proposed_solution.percent_match.present? ? percent_match = proposed_solution.percent_match : 0
                      - case percent_match
                      - when 0.to_f.next_float..50
                        - class_name = 'danger'
                      - when 50.to_f.next_float..60
                        - class_name = 'warning'
                      - when 60.to_f.next_float..70
                        - class_name = 'info'
                      - when 70.to_f.next_float..100
                        - class_name = 'success'
                      .progress
                        .progress-bar.progress-bar-striped{ 'aria-valuemax': '100', 'aria-valuemin': '0', 'aria-valuenow': percent_match, role: 'progressbar', style: "width: #{percent_match}%", class: "progress-bar-#{class_name}" }
                          %span #{proposed_solution.percent_match}%

app/views/campaigns/show.html.haml
.container
  .row
    .col-md-offset-1.col-md-10
      .panel.panel-default
        .panel-heading.flex-panel-heading
          %h2= @campaign.title
          .countdown.text-center
            - if @campaign.expired?
              %p Please Note: This campaign has expired.
            - elsif @campaign.pending?
              %p Please Note: This campaign is pending.
            - elsif @campaign.active?
              %strong.expires-at{ data: { countdown: @campaign.expires_at } }

        .panel-body
          = image_tag(@campaign.featured_image.url(:medium), class: 'img-responsive', style: 'margin: 0 auto;')
          %h2 Our Company
          = raw @campaign.company_description
          %h2 Our Needs
          = raw @campaign.company_needs
          %h2 Our Challenges
          = raw @campaign.company_challenges
          .opportunity-detail
            %h2 Opportunity Details
          .row
            .col-md-4
              %p Sector:
            .col-md-8
              %p= @campaign.sector.values.map(&:text).join(', ')
          .row
            .col-md-4
              %p Company Headquarters:
            .col-md-8
              %p= @campaign.country
          .row
            .col-md-4
              %p Targeted Time To Market:
            .col-md-8
              %p= @campaign.targeted_time_to_market
          .row
            .col-md-4
              %p{ style: 'display: inline-block' } Expected TRL:
              = link_to '#', style: 'display: inline-block' do
                %sup= fa_icon 'info-circle', class: 'fa-2x trl-modal'
            .col-md-8
              %p= @campaign.expected_trl
          %br
          %span.like-unlike-container
            = link_to '#', class: 'add-to-favorites', style: (current_user.likes.where(campaign_id: @campaign.id).present? ? 'display:none;' : '').to_s, data: { campaign_id: @campaign.id, url: add_to_favorites_path } do
              = fa_icon 'heart'
              %p{ style: 'display: inline-block;' } Add To Favorites

            = link_to '#', class: 'remove-from-favorites', style: (current_user.likes.where(campaign_id: @campaign.id).present? ? '' : 'display:none;').to_s, data: { campaign_id: @campaign.id, url: remove_from_favorites_path } do
              = fa_icon 'heart', class: 'red-heart'
              %p{ style: 'display: inline-block;' } Remove From Favorites

          .text-center
            - if current_user.role == :tech_provider && @campaign.active?
              = link_to 'Apply Now', new_campaign_proposed_solution_path(@campaign), class: 'btn btn-primary'
            - elsif current_user.role == :tech_seeker
              = link_to 'View Campaign Performance', performance_campaign_path, class: 'btn btn-primary'