config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/devise/registrations'
  }

  devise_for :admins, skip: [:registrations]

  # needs to be AFTER "devise_for :admins" otherwise the admin routes will be messed up
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticate :user do
    resources :campaigns, only: [:index, :show] do
      member do
        get '/performance' => 'campaigns#performance', as: 'performance'
      end
      resources :proposed_solutions, only: [:new, :create]
      collection do
        get '/search' => 'search#find_campaigns', as: 'search'
      end
    end
    resources :favorites, only: [:index]
    scope '/favorites' do
      post '/add-to-favorites' => 'favorites#add_to_favorites'
      delete '/remove-from-favorites' => 'favorites#remove_from_favorites'
    end
  end

  authenticated :user do
    root to: 'campaigns#index', as: :authenticated_root
  end

  root 'home#index'
end

app/views/layouts/_footer.html.haml
.footer
  .row.footer-content
    .col-md-3
      %h3 CONTACT
      %p.address Baehl Innovation
      %p.address 26th Floor, Montparnasse Tower
      %p.address 33 Avenue du Maine
      %p.address 75015 Paris
      %p.address Telephone: +33 (0)1 44 10 41 43

    .col-md-5
      %h3 RECENT TWEETS
      %a.twitter-timeline{ data: { 'tweet-limit': 1, 'chrome': 'transparent noborders nofooter noheader', 'link-color': '#f1f1f1' }, href: 'https://twitter.com/baehlinnovation' } Tweets by Baehl Innovation
      %script{ async: true, src: '//platform.twitter.com/widgets.js', charset: 'utf-8' }

    .col-md-4
      %h3 LEGAL INFORMATION
      %p Copyright 2015 - 2016 Baehl Innovation
      %p All Rights Reserved
      = link_to 'Mentions Légales', 'http://baehl-innovation.com/mentions-legales/', class: 'footer-link'
      .social-icons
        = link_to 'https://twitter.com/baehlinnovation' do
          = fa_icon 'twitter-square', class: 'fa-2x'
        = link_to 'https://www.linkedin.com/company/baehl-innovation' do
          = fa_icon 'linkedin-square', class: 'fa-2x'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}" }
      %button.close{ 'aria hidden': 'true', 'data dismiss': 'alert', type: 'button' }&times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  = link_to '#', class: 'navbar-link text-center phone-icon-link hidden-xs hidden-sm' do
    = fa_icon 'phone', class: 'fa-3x'
    %p +33 (0)1 44 10 41 43
  = link_to favorites_path, class: 'navbar-link text-center hidden-xs hidden-sm' do
    = fa_icon 'heart', class: 'fa-3x'
    %p My Favorites
  = link_to '#', class: 'navbar-link text-center dropdownmenu hidden-xs hidden-sm' do
    = fa_icon 'bars', class: 'fa-3x'
    %p My Account
  = link_to '#', class: 'navbar-link text-center dropdownmenu visible-xs visible-sm' do
    = fa_icon 'bars', class: 'fa-3x'
  .profile-dropdown.hidden
    = link_to '#', class: 'navbar-link text-center phone-icon-link visible-xs visible-sm dropdown-link' do
      %p Contact
    = link_to favorites_path, class: 'navbar-link text-center visible-xs visible-sm dropdown-link' do
      %p My Favorites
    = link_to 'My Profile', edit_user_registration_path, class: 'navbar-link dropdown-link'
    = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'navbar-link dropdown-link'
- else
  = render 'layouts/navigation_links'

app/views/layouts/_navigation.html.haml
- unless user_signed_in?
  %nav.navbar.primary
    %p.contact-us.pull-left Contact Us Today! +33 (0)1 44 10 41 43
    .social-icons.pull-right
      = link_to 'https://twitter.com/baehlinnovation' do
        = fa_icon 'twitter-square', class: 'fa-2x'
      = link_to 'https://www.linkedin.com/company/baehl-innovation' do
        = fa_icon 'linkedin-square', class: 'fa-2x'

%nav.navbar.secondary
  = link_to root_path, class: 'navbar-logo pull-left' do
    = image_tag('logo.png', class: 'img-responsive')

  .navbar-links.pull-right
    = render 'layouts/nav_links_for_auth'

- if user_signed_in?
  = render 'layouts/tertiary_navigation'

app/views/layouts/_navigation_links.html.haml
= link_to 'Home', root_path, class: 'navbar-link-home dropdown-link hidden-xs hidden-sm'
= link_to 'Baehl Innovation', 'http://baehl-innovation.com', class: 'navbar-link-home dropdown-link hidden-xs hidden-sm'
= link_to 'Who', 'http://baehl-innovation.com/who-we-are', class: 'navbar-link-home dropdown-link hidden-xs hidden-sm'
= link_to 'What', 'http://baehl-innovation.com/bbh', class: 'navbar-link-home dropdown-link hidden-xs hidden-sm'
= link_to 'Where', 'http://baehl-innovation.com/where-we-work', class: 'navbar-link-home dropdown-link hidden-xs hidden-sm'
= link_to 'Contact', 'http://baehl-innovation.com/contact', class: 'navbar-link-home dropdown-link hidden-xs hidden-sm'

= link_to '#', class: 'navbar-link-hamburger text-center dropdownmenu visible-xs visible-sm' do
  = fa_icon 'bars', class: 'fa-3x'
.regular-dropdown.hidden
  = link_to 'Home', root_path, class: 'navbar-link-home dropdown-link'
  = link_to 'Baehl Innovation', 'http://baehl-innovation.com', class: 'navbar-link-home dropdown-link'
  = link_to 'Who', 'http://baehl-innovation.com/who-we-are', class: 'navbar-link-home dropdown-link'
  = link_to 'What', 'http://baehl-innovation.com/bbh', class: 'navbar-link-home dropdown-link'
  = link_to 'Where', 'http://baehl-innovation.com/where-we-work', class: 'navbar-link-home dropdown-link'
  = link_to 'Contact', 'http://baehl-innovation.com/contact', class: 'navbar-link-home dropdown-link'

app/views/layouts/_tertiary_navigation.html.haml
%nav.navbar.tertiary
  %p.home.pull-left
    = link_to 'Home', root_path, class: 'home-link'
    = link_to '#' do
      = fa_icon 'info-circle', class: 'fa-2x contact'
  - if "#{controller_name} #{action_name}" == 'campaigns index'
    .search-campaigns.pull-right
      .search-container
        = select_tag :country, options_for_select(Campaign.country_options.map { |hash| [hash[:id], hash[:text]] }), include_blank: 'Select Country', class: 'select2-country country-search', data: { url: search_campaigns_path }
      .search-container
        = select_tag :order, options_for_select([['Ending Last', 'DESC'], ['Ending Soonest', 'ASC']]), include_blank: 'Select Order', class: 'select2 order-search', data: { url: search_campaigns_path }
      .search-container
        = select_tag :sector, options_for_select(Campaign.sector.values.map { |v| [v.text, v.value] }), include_blank: 'Select Sector', class: 'select2 sector-search', data: { url: search_campaigns_path }
  %p.back-to-listings.pull-right.hidden-xs.hidden-sm
    - unless "#{controller_name} #{action_name}" == 'campaigns index'
      = fa_icon 'fast-backward'
      = link_to 'Back to All Campaign Listings', root_path
    - if @proposed_solution.present?
      = fa_icon 'step-backward'
      = link_to 'Back to Campaign', campaign_path(@proposed_solution.campaign)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    %title= content_for?(:title) ? yield(:title) : 'Baehl Business Hub'
    %meta{ name: 'description', content: (content_for?(:description) ? yield(:description) : 'Baehl Business Hub').to_s }
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans'
    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway:800'
    = javascript_include_tag 'application'
    = favicon_link_tag 'favicon-logo.png', type: 'image/png'
    = csrf_meta_tags
  %body{ class:  "#{controller_path.tr('_', '-').tr('/', '-')} #{action_name.tr('_', '-')}" }
    .wrapper
      %main{ role: 'main' }
        = render 'layouts/messages'
        = render 'layouts/navigation'
        .content
          = yield
        = render 'layouts/footer'